package command

import (
	"github.com/mailgun/vulcand/Godeps/_workspace/src/github.com/codegangsta/cli"

	"github.com/mailgun/vulcand/engine"
)

func NewServerCommand(cmd *Command) cli.Command {
	return cli.Command{
		Name:  "endpoint",
		Usage: "Operations with vulcan endpoint",
		Subcommands: []cli.Command{
			{
				Name:   "add",
				Usage:  "Add a new endpoint to location",
				Action: cmd.upsertServerAction,
				Flags: []cli.Flag{
					cli.StringFlag{Name: "id", Usage: "endpoint id, autogenerated if empty"},
					cli.StringFlag{Name: "backend, b", Usage: "backend id"},
					cli.StringFlag{Name: "url", Usage: "url in form <scheme>://<host>:<port>"},
					cli.DurationFlag{Name: "ttl", Usage: "ttl"},
				},
			},
			{
				Name:  "rm",
				Usage: "Remove endpoint from location",
				Flags: []cli.Flag{
					cli.StringFlag{Name: "id", Usage: "endpoint id"},
					cli.StringFlag{Name: "upstream, up", Usage: "upstream id"},
				},
				Action: cmd.deleteServerAction,
			},
		},
	}
}

func (cmd *Command) upsertServerAction(c *cli.Context) {
	s, err := engine.NewServer(c.String("id"), c.String("url"))
	if err != nil {
		cmd.printError(err)
		return
	}
	if err := cmd.client.UpsertServer(engine.BackendKey{Id: c.String("backend")}, *s, c.Duration("ttl")); err != nil {
		cmd.printError(err)
		return
	}
	cmd.printOk("server upserted")
}

func (cmd *Command) deleteServerAction(c *cli.Context) {
	sk := engine.ServerKey{BackendKey: engine.BackendKey{Id: c.String("backend")}, Id: c.String("id")}
	if err := cmd.client.DeleteServer(sk); err != nil {
		cmd.printError(err)
		return
	}
	cmd.printOk("Server %v deleted", sk.Id)
}
